version: '3.7'

services:
    backend:
        env_file:
            - ./blog_ke_backend/.env
        build:
            context: ./blog_ke_backend
            dockerfile: Dockerfile
            target: development
        container_name: backend
        restart: unless-stopped
        working_dir: /blog_ke_backend
        volumes:
            - ./blog_ke_backend:/blog_ke_backend
        expose:
            - 8000
        networks:
            - back-tier

    db:
        image: postgres
        restart: unless-stopped
        container_name: db
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=blog_ke
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password123
        expose:
            - 5432
        networks:
            - back-tier

    frontend:
        build: blog_ke_frontend
        container_name: frontend
        restart: unless-stopped
        working_dir: /blog_ke_frontend
        volumes:
            - ./blog_ke_frontend:/blog_ke_frontend
        command: npm run start
        expose:
            - 3000
        networks:
            - front-tire

    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        container_name: nginx
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./blog_ke_backend/static/:/data/static/
            - ./blog_ke_backend/media/:/data/media/
        networks:
            - back-tier
            - front-tire
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

networks:
    front-tire: {}
    back-tier: {}